/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_school21_webcalculator_models_CreditCalc */

#ifndef _Included_ru_school21_webcalculator_models_CreditCalc
#define _Included_ru_school21_webcalculator_models_CreditCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_school21_webcalculator_models_CreditCalc
 * Method:    createPayments
 * Signature: (DIDI)V
 */
JNIEXPORT void JNICALL Java_ru_school21_webcalculator_models_CreditCalc_createPayments
  (JNIEnv *, jobject, jdouble, jint, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
